<?php
declare(strict_types=1);

// Belkavpn SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

BelkavpnUtility::setRegistrar(function (BelkavpnUtility $u): void {
    $u->clean = [BelkavpnClean::class, 'call'];
    $u->done = [BelkavpnDone::class, 'call'];
    $u->make_error = [BelkavpnMakeError::class, 'call'];
    $u->feature_add = [BelkavpnFeatureAdd::class, 'call'];
    $u->feature_hook = [BelkavpnFeatureHook::class, 'call'];
    $u->feature_init = [BelkavpnFeatureInit::class, 'call'];
    $u->fetcher = [BelkavpnFetcher::class, 'call'];
    $u->make_fetch_def = [BelkavpnMakeFetchDef::class, 'call'];
    $u->make_context = [BelkavpnMakeContext::class, 'call'];
    $u->make_options = [BelkavpnMakeOptions::class, 'call'];
    $u->make_request = [BelkavpnMakeRequest::class, 'call'];
    $u->make_response = [BelkavpnMakeResponse::class, 'call'];
    $u->make_result = [BelkavpnMakeResult::class, 'call'];
    $u->make_point = [BelkavpnMakePoint::class, 'call'];
    $u->make_spec = [BelkavpnMakeSpec::class, 'call'];
    $u->make_url = [BelkavpnMakeUrl::class, 'call'];
    $u->param = [BelkavpnParam::class, 'call'];
    $u->prepare_auth = [BelkavpnPrepareAuth::class, 'call'];
    $u->prepare_body = [BelkavpnPrepareBody::class, 'call'];
    $u->prepare_headers = [BelkavpnPrepareHeaders::class, 'call'];
    $u->prepare_method = [BelkavpnPrepareMethod::class, 'call'];
    $u->prepare_params = [BelkavpnPrepareParams::class, 'call'];
    $u->prepare_path = [BelkavpnPreparePath::class, 'call'];
    $u->prepare_query = [BelkavpnPrepareQuery::class, 'call'];
    $u->graphql_body = [BelkavpnGraphql::class, 'body'];
    $u->graphql_errors = [BelkavpnGraphql::class, 'errors'];
    $u->result_basic = [BelkavpnResultBasic::class, 'call'];
    $u->result_body = [BelkavpnResultBody::class, 'call'];
    $u->result_headers = [BelkavpnResultHeaders::class, 'call'];
    $u->transform_request = [BelkavpnTransformRequest::class, 'call'];
    $u->transform_response = [BelkavpnTransformResponse::class, 'call'];
});
